### ISSUE TITLE
 向下滑动到底部的时候 异常退出

### ISSUE THREAD

**Issue by xiantang** [wzbcCoder/ZhiHuDaily#25]

**Comment by xiantang** [comment]
12-03 01:55:27.964 23545-23545/com.example.administrator.zhihunews E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.example.administrator.zhihunews, PID: 23545
                                                                                     java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
                                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                         at java.util.ArrayList.get(ArrayList.java:308)
                                                                                         at com.example.administrator.zhihunews.adapter.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:48)
                                                                                         at com.example.administrator.zhihunews.adapter.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:21)
                                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                                         at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                                         at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                                         at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                                         at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                                         at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by xiantang** [comment]
通过修改为真实位置 解决
